### PR TITLE
Wall of fame

### PR DESCRIPTION
**Pull request by HargulS**

### CODE REVIEW

**Comment by HargulS** [comment]
1. I commented out the "process.env.port" I am not sure how would that work. You can change this back to the way you want and make the necessary changes in the frontend.
2. The cards are not fully designed yet. I will work on that 
3.  I will also work on the adding the upload functionality for the images

**Comment by zaycation** [comment]
Great. We will wait to merge the PR once everything is complete. Also, please try and get rid of all warning messages when compiling the code. If any warnings our present, it will mess up the CI deployment via nelify.

**Comment by zaycation** [comment]
Also, we want to keep process.env and app.listen method as it was before since we want to use port 5000 and we will most likely host backend for free via heroku.

**Comment by HargulS** [comment]
> 
> 
> Great. We will wait to merge the PR once everything is complete. Also, please try and get rid of all warning messages when compiling the code. If any warnings our present, it will mess up the CI deployment via nelify.

There are 2 Warning messages and 1 Error on Chrome.  Warnings are 
1. _Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>_. 
2. _Warning: Legacy context API has been detected within a strict-mode tree._
They both appear in the files other than mine.  Also, I am not sure how to correct them. 

Error:
1. _componentWillReceiveProps has been renamed_
I downloaded `npx react-codemod rename-unsafe-lifecycles` but the error is still there. From what I am reading it should be removed once the repos are merged. 

Let me know if more needs to be done regarding this.

**Comment by HargulS** [comment]
> 
> 
> Also, we want to keep process.env and app.listen method as it was before since we want to use port 5000 and we will most likely host backend for free via heroku.

This is resolved. The coded is reverted back to port 5000. :)

**Comment by zaycation** [comment]
@HargulS Looks pretty good! We need to now implement a way for contributorsData.json to use maybe our github profile pictures as our images within the contributor cards.

Also, only an admin account or something should be allowed to add contributors. Since at the moment anyone can do it.

**Comment by HargulS** [comment]
> 
> 
> @HargulS Looks pretty good! We need to now implement a way for contributorsData.json to use maybe our github profile pictures as our images within the contributor cards.
> 
> Also, only an admin account or something should be allowed to add contributors. Since at the moment anyone can do it.

@zaycation You are right I was thinking on the similar lines.  I am still new to coding and react so help me understand how this would work.  This what I am thinking:
1. Set up admin page 
2. You have the contributors' github usernames
3. Setting up some authentication/ API to fetch the profiles pictures from Github 

Am I on the right track here?

**Pull request merged**
